// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityFormController from "./activity_form_controller"
application.register("activity-form", ActivityFormController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AnnualCoursesController from "./annual_courses_controller"
application.register("annual-courses", AnnualCoursesController)

import AnnualEnrollmentsFormController from "./annual_enrollments_form_controller"
application.register("annual-enrollments-form", AnnualEnrollmentsFormController)

import CampCoursesController from "./camp_courses_controller"
application.register("camp-courses", CampCoursesController)

import ClickableTableController from "./clickable_table_controller"
application.register("clickable-table", ClickableTableController)

import CloseModalController from "./close_modal_controller"
application.register("close-modal", CloseModalController)

import CoachCoursesController from "./coach_courses_controller"
application.register("coach-courses", CoachCoursesController)

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import EnrollmentFormController from "./enrollment_form_controller"
application.register("enrollment-form", EnrollmentFormController)

import FilterCoachController from "./filter_coach_controller"
application.register("filter-coach", FilterCoachController)

import FilterMembershipDepositController from "./filter_membership_deposit_controller"
application.register("filter-membership-deposit", FilterMembershipDepositController)

import FlashesController from "./flashes_controller"
application.register("flashes", FlashesController)

import Form__AutoSubmitController from "./form/auto_submit_controller"
application.register("form--auto-submit", Form__AutoSubmitController)

import Form__Enrollment__CampController from "./form/enrollment/camp_controller"
application.register("form--enrollment--camp", Form__Enrollment__CampController)

import HiddenFormsController from "./hidden_forms_controller"
application.register("hidden-forms", HiddenFormsController)

import ImportCsvController from "./import_csv_controller"
application.register("import-csv", ImportCsvController)

import LoadingMessageController from "./loading_message_controller"
application.register("loading-message", LoadingMessageController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PastAnnualCoursesController from "./past_annual_courses_controller"
application.register("past-annual-courses", PastAnnualCoursesController)

import PastCampCoursesController from "./past_camp_courses_controller"
application.register("past-camp-courses", PastCampCoursesController)

import PaymentMethodController from "./payment_method_controller"
application.register("payment-method", PaymentMethodController)

import SchoolPeriodPriceController from "./school_period_price_controller"
application.register("school-period-price", SchoolPeriodPriceController)

import SearchCoachController from "./search_coach_controller"
application.register("search-coach", SearchCoachController)

import SearchStudentController from "./search_student_controller"
application.register("search-student", SearchStudentController)

import SelectedButtonController from "./selected_button_controller"
application.register("selected-button", SelectedButtonController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import UpdatePhotoFromCourseController from "./update_photo_from_course_controller"
application.register("update-photo-from-course", UpdatePhotoFromCourseController)

import UploadPhotoController from "./upload_photo_controller"
application.register("upload-photo", UploadPhotoController)
