// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityFormController from "./activity_form_controller"
application.register("activity-form", ActivityFormController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AnnualCoursesController from "./annual_courses_controller"
application.register("annual-courses", AnnualCoursesController)

import AnnualEnrollmentsFormController from "./annual_enrollments_form_controller"
application.register("annual-enrollments-form", AnnualEnrollmentsFormController)

import CampCoursesController from "./camp_courses_controller"
application.register("camp-courses", CampCoursesController)

import ClickableTableController from "./clickable_table_controller"
application.register("clickable-table", ClickableTableController)

import CoachCoursesController from "./coach_courses_controller"
application.register("coach-courses", CoachCoursesController)

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import EnrollmentFormController from "./enrollment_form_controller"
application.register("enrollment-form", EnrollmentFormController)

import FilterCoachController from "./filter_coach_controller"
application.register("filter-coach", FilterCoachController)

import FilterMembershipDepositController from "./filter_membership_deposit_controller"
application.register("filter-membership-deposit", FilterMembershipDepositController)

import HiddenFormsController from "./hidden_forms_controller"
application.register("hidden-forms", HiddenFormsController)

import ImportCsvController from "./import_csv_controller"
application.register("import-csv", ImportCsvController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PastAnnualCoursesController from "./past_annual_courses_controller"
application.register("past-annual-courses", PastAnnualCoursesController)

import PastCampCoursesController from "./past_camp_courses_controller"
application.register("past-camp-courses", PastCampCoursesController)

import PresenceSheetController from "./presence_sheet_controller"
application.register("presence-sheet", PresenceSheetController)

import SearchCoachController from "./search_coach_controller"
application.register("search-coach", SearchCoachController)

import SearchStudentController from "./search_student_controller"
application.register("search-student", SearchStudentController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import UpdatePhotoFromCourseController from "./update_photo_from_course_controller"
application.register("update-photo-from-course", UpdatePhotoFromCourseController)

import UploadPhotoController from "./upload_photo_controller"
application.register("upload-photo", UploadPhotoController)
