UpdateActivityStatsJob:
  cron: "00 23 * * *"
  class: UpdateActivityStatsJob
UpdateCampStatsJob:
  cron: "10 23 * * *"
  class: UpdateCampStatsJob
UpdateSchoolPeriodStatsJob:
  cron: "20 23 * * *"
  class: UpdateSchoolPeriodStatsJob
UpdateAnnualProgramStatsJob:
  cron: "30 23 * * *"
  class: UpdateAnnualProgramStatsJob
